// The widget extension (generated by expo-widgets) reads what the app hands over from UserDefaults shared through the
// app group. Apple requires every bundle that uses a "required reason" API to say why in its own privacy manifest,
// and expo-widgets doesn't ship one, so this adds PrivacyInfo.xcprivacy to the extension: shared app-group defaults
// (1C8F.1), no tracking, nothing collected. Without it App Store Connect warns (ITMS-91053) on upload.
const fs = require('fs');
const path = require('path');
const { withDangerousMod, withXcodeProject } = require('expo/config-plugins');

const TARGET = 'ExpoWidgetsTarget';
const FILE = 'PrivacyInfo.xcprivacy';
const MANIFEST = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>NSPrivacyTracking</key>
  <false/>
  <key>NSPrivacyTrackingDomains</key>
  <array/>
  <key>NSPrivacyCollectedDataTypes</key>
  <array/>
  <key>NSPrivacyAccessedAPITypes</key>
  <array>
    <dict>
      <key>NSPrivacyAccessedAPIType</key>
      <string>NSPrivacyAccessedAPICategoryUserDefaults</string>
      <key>NSPrivacyAccessedAPITypeReasons</key>
      <array>
        <string>1C8F.1</string>
      </array>
    </dict>
  </array>
</dict>
</plist>
`;

function withManifestFile(config) {
  return withDangerousMod(config, ['ios', async cfg => {
    const dir = path.join(cfg.modRequest.platformProjectRoot, TARGET);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, FILE), MANIFEST);
    return cfg;
  }]);
}

function withManifestInTarget(config) {
  return withXcodeProject(config, cfg => {
    const project = cfg.modResults;
    const target = project.pbxTargetByName(TARGET) && Object.entries(project.pbxNativeTargetSection())
      .find(([, t]) => typeof t === 'object' && t.name === TARGET);
    if (!target) return cfg;                         // no widgets configured: nothing to do
    const [targetUuid] = target;
    const already = Object.values(project.pbxFileReferenceSection()).some(f => typeof f === 'object' && f.path && String(f.path).replace(/"/g, '').endsWith(FILE) && String(f.path).includes(TARGET));
    if (already) return cfg;
    const groupKey = project.findPBXGroupKey({ name: TARGET }) || project.findPBXGroupKey({ path: TARGET });
    // Inside the extension's group the path is relative to it; otherwise relative to ios/
    const file = project.addFile(groupKey ? FILE : `${TARGET}/${FILE}`, groupKey, { lastKnownFileType: 'text.xml' });
    if (!file) return cfg;
    file.uuid = project.generateUuid();
    file.target = targetUuid;
    project.addToPbxBuildFileSection(file);
    const resources = () => {
      const phases = project.hash.project.objects.PBXResourcesBuildPhase || {};
      return (project.pbxNativeTargetSection()[targetUuid].buildPhases || []).map(p => phases[p.value]).find(Boolean);
    };
    if (!resources()) project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', targetUuid);
    resources().files.push({ value: file.uuid, comment: `${FILE} in Resources` });
    return cfg;
  });
}

module.exports = function withWidgetPrivacyManifest(config) {
  return withManifestInTarget(withManifestFile(config));
};
